EPMDJ-9510 Add Swagger UI
Drill4J/spring-petclinic pull request #14
Opened 2021-12-30 13:30 UTC by kir-r

2022-01-11 13:35 UTC, LikhanovMaxim requested changes

2022-01-11 13:35 UTC, LikhanovMaxim commented on pom.xml
>  <project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
add to readme - URL to swagger

2022-01-11 13:35 UTC, LikhanovMaxim commented on src/main/java/org/springframework/samples/petclinic/coverage/BasicConstructionsController.java
> +            "Method returns its text value.")
maybe add desc about coverage / count probes / bytecode?

2022-01-11 13:35 UTC, LikhanovMaxim commented on src/main/java/org/springframework/samples/petclinic/coverage/BasicConstructionsController.java
> +            "Method returns its text value.")
in another endpoints the same

2022-01-31 13:59 UTC, LikhanovMaxim approved these changes

2022-01-31 14:07 UTC, ViktoriiaLebedeva approved these changes

2022-01-31 14:07 UTC, ViktoriiaLebedeva commented on src/main/java/org/springframework/samples/petclinic/coverage/BasicConstructionsController.java
> +
remove new line

2022-02-08 12:01 UTC, merged